package ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tbl_commune".
 */
public class Commune {

    /** Not-null value. */
    private String ComId;
    private String ComNom;
    /** Not-null value. */
    private String DeptId;

    public Commune() {
    }

    public Commune(String ComId, String ComNom, String DeptId) {
        this.ComId = ComId;
        this.ComNom = ComNom;
        this.DeptId = DeptId;
    }

    /** Not-null value. */
    public String getComId() {
        return ComId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setComId(String ComId) {
        this.ComId = ComId;
    }

    public String getComNom() {
        return ComNom;
    }

    public void setComNom(String ComNom) {
        this.ComNom = ComNom;
    }

    /** Not-null value. */
    public String getDeptId() {
        return DeptId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDeptId(String DeptId) {
        this.DeptId = DeptId;
    }

}
