package ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.Personnel;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.FormulaireExercices;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.Agent_Evaluation_Exercices;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.Question_FormulaireExercices;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.Questions;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.Reponses;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.JustificationReponses;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.ReponseEntree;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.AgentRapport;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.Departement;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.Commune;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.Vqse;

import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.PersonnelDao;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.FormulaireExercicesDao;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.Agent_Evaluation_ExercicesDao;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.Question_FormulaireExercicesDao;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.QuestionsDao;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.ReponsesDao;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.JustificationReponsesDao;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.ReponseEntreeDao;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.AgentRapportDao;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.DepartementDao;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.CommuneDao;
import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.VqseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personnelDaoConfig;
    private final DaoConfig formulaireExercicesDaoConfig;
    private final DaoConfig agent_Evaluation_ExercicesDaoConfig;
    private final DaoConfig question_FormulaireExercicesDaoConfig;
    private final DaoConfig questionsDaoConfig;
    private final DaoConfig reponsesDaoConfig;
    private final DaoConfig justificationReponsesDaoConfig;
    private final DaoConfig reponseEntreeDaoConfig;
    private final DaoConfig agentRapportDaoConfig;
    private final DaoConfig departementDaoConfig;
    private final DaoConfig communeDaoConfig;
    private final DaoConfig vqseDaoConfig;

    private final PersonnelDao personnelDao;
    private final FormulaireExercicesDao formulaireExercicesDao;
    private final Agent_Evaluation_ExercicesDao agent_Evaluation_ExercicesDao;
    private final Question_FormulaireExercicesDao question_FormulaireExercicesDao;
    private final QuestionsDao questionsDao;
    private final ReponsesDao reponsesDao;
    private final JustificationReponsesDao justificationReponsesDao;
    private final ReponseEntreeDao reponseEntreeDao;
    private final AgentRapportDao agentRapportDao;
    private final DepartementDao departementDao;
    private final CommuneDao communeDao;
    private final VqseDao vqseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personnelDaoConfig = daoConfigMap.get(PersonnelDao.class).clone();
        personnelDaoConfig.initIdentityScope(type);

        formulaireExercicesDaoConfig = daoConfigMap.get(FormulaireExercicesDao.class).clone();
        formulaireExercicesDaoConfig.initIdentityScope(type);

        agent_Evaluation_ExercicesDaoConfig = daoConfigMap.get(Agent_Evaluation_ExercicesDao.class).clone();
        agent_Evaluation_ExercicesDaoConfig.initIdentityScope(type);

        question_FormulaireExercicesDaoConfig = daoConfigMap.get(Question_FormulaireExercicesDao.class).clone();
        question_FormulaireExercicesDaoConfig.initIdentityScope(type);

        questionsDaoConfig = daoConfigMap.get(QuestionsDao.class).clone();
        questionsDaoConfig.initIdentityScope(type);

        reponsesDaoConfig = daoConfigMap.get(ReponsesDao.class).clone();
        reponsesDaoConfig.initIdentityScope(type);

        justificationReponsesDaoConfig = daoConfigMap.get(JustificationReponsesDao.class).clone();
        justificationReponsesDaoConfig.initIdentityScope(type);

        reponseEntreeDaoConfig = daoConfigMap.get(ReponseEntreeDao.class).clone();
        reponseEntreeDaoConfig.initIdentityScope(type);

        agentRapportDaoConfig = daoConfigMap.get(AgentRapportDao.class).clone();
        agentRapportDaoConfig.initIdentityScope(type);

        departementDaoConfig = daoConfigMap.get(DepartementDao.class).clone();
        departementDaoConfig.initIdentityScope(type);

        communeDaoConfig = daoConfigMap.get(CommuneDao.class).clone();
        communeDaoConfig.initIdentityScope(type);

        vqseDaoConfig = daoConfigMap.get(VqseDao.class).clone();
        vqseDaoConfig.initIdentityScope(type);

        personnelDao = new PersonnelDao(personnelDaoConfig, this);
        formulaireExercicesDao = new FormulaireExercicesDao(formulaireExercicesDaoConfig, this);
        agent_Evaluation_ExercicesDao = new Agent_Evaluation_ExercicesDao(agent_Evaluation_ExercicesDaoConfig, this);
        question_FormulaireExercicesDao = new Question_FormulaireExercicesDao(question_FormulaireExercicesDaoConfig, this);
        questionsDao = new QuestionsDao(questionsDaoConfig, this);
        reponsesDao = new ReponsesDao(reponsesDaoConfig, this);
        justificationReponsesDao = new JustificationReponsesDao(justificationReponsesDaoConfig, this);
        reponseEntreeDao = new ReponseEntreeDao(reponseEntreeDaoConfig, this);
        agentRapportDao = new AgentRapportDao(agentRapportDaoConfig, this);
        departementDao = new DepartementDao(departementDaoConfig, this);
        communeDao = new CommuneDao(communeDaoConfig, this);
        vqseDao = new VqseDao(vqseDaoConfig, this);

        registerDao(Personnel.class, personnelDao);
        registerDao(FormulaireExercices.class, formulaireExercicesDao);
        registerDao(Agent_Evaluation_Exercices.class, agent_Evaluation_ExercicesDao);
        registerDao(Question_FormulaireExercices.class, question_FormulaireExercicesDao);
        registerDao(Questions.class, questionsDao);
        registerDao(Reponses.class, reponsesDao);
        registerDao(JustificationReponses.class, justificationReponsesDao);
        registerDao(ReponseEntree.class, reponseEntreeDao);
        registerDao(AgentRapport.class, agentRapportDao);
        registerDao(Departement.class, departementDao);
        registerDao(Commune.class, communeDao);
        registerDao(Vqse.class, vqseDao);
    }
    
    public void clear() {
        personnelDaoConfig.getIdentityScope().clear();
        formulaireExercicesDaoConfig.getIdentityScope().clear();
        agent_Evaluation_ExercicesDaoConfig.getIdentityScope().clear();
        question_FormulaireExercicesDaoConfig.getIdentityScope().clear();
        questionsDaoConfig.getIdentityScope().clear();
        reponsesDaoConfig.getIdentityScope().clear();
        justificationReponsesDaoConfig.getIdentityScope().clear();
        reponseEntreeDaoConfig.getIdentityScope().clear();
        agentRapportDaoConfig.getIdentityScope().clear();
        departementDaoConfig.getIdentityScope().clear();
        communeDaoConfig.getIdentityScope().clear();
        vqseDaoConfig.getIdentityScope().clear();
    }

    public PersonnelDao getPersonnelDao() {
        return personnelDao;
    }

    public FormulaireExercicesDao getFormulaireExercicesDao() {
        return formulaireExercicesDao;
    }

    public Agent_Evaluation_ExercicesDao getAgent_Evaluation_ExercicesDao() {
        return agent_Evaluation_ExercicesDao;
    }

    public Question_FormulaireExercicesDao getQuestion_FormulaireExercicesDao() {
        return question_FormulaireExercicesDao;
    }

    public QuestionsDao getQuestionsDao() {
        return questionsDao;
    }

    public ReponsesDao getReponsesDao() {
        return reponsesDao;
    }

    public JustificationReponsesDao getJustificationReponsesDao() {
        return justificationReponsesDao;
    }

    public ReponseEntreeDao getReponseEntreeDao() {
        return reponseEntreeDao;
    }

    public AgentRapportDao getAgentRapportDao() {
        return agentRapportDao;
    }

    public DepartementDao getDepartementDao() {
        return departementDao;
    }

    public CommuneDao getCommuneDao() {
        return communeDao;
    }

    public VqseDao getVqseDao() {
        return vqseDao;
    }

}
