package ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tbl_departement".
 */
public class Departement {

    /** Not-null value. */
    private String DeptId;
    private String DeptNom;

    public Departement() {
    }

    public Departement(String DeptId, String DeptNom) {
        this.DeptId = DeptId;
        this.DeptNom = DeptNom;
    }

    /** Not-null value. */
    public String getDeptId() {
        return DeptId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDeptId(String DeptId) {
        this.DeptId = DeptId;
    }

    public String getDeptNom() {
        return DeptNom;
    }

    public void setDeptNom(String DeptNom) {
        this.DeptNom = DeptNom;
    }

}
