package ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Tbl_FormulaireExercices".
 */
public class FormulaireExercices {

    private Long codeExercice;
    private String libelleExercice;
    private String descriptions;
    private String instructions;
    private String rappelExercice;
    private String typeEvaluation;
    private String statut;
    private String dureeEnSeconde;

    public FormulaireExercices() {
    }

    public FormulaireExercices(Long codeExercice) {
        this.codeExercice = codeExercice;
    }

    public FormulaireExercices(Long codeExercice, String libelleExercice, String descriptions, String instructions, String rappelExercice, String typeEvaluation, String statut, String dureeEnSeconde) {
        this.codeExercice = codeExercice;
        this.libelleExercice = libelleExercice;
        this.descriptions = descriptions;
        this.instructions = instructions;
        this.rappelExercice = rappelExercice;
        this.typeEvaluation = typeEvaluation;
        this.statut = statut;
        this.dureeEnSeconde = dureeEnSeconde;
    }

    public Long getCodeExercice() {
        return codeExercice;
    }

    public void setCodeExercice(Long codeExercice) {
        this.codeExercice = codeExercice;
    }

    public String getLibelleExercice() {
        return libelleExercice;
    }

    public void setLibelleExercice(String libelleExercice) {
        this.libelleExercice = libelleExercice;
    }

    public String getDescriptions() {
        return descriptions;
    }

    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }

    public String getInstructions() {
        return instructions;
    }

    public void setInstructions(String instructions) {
        this.instructions = instructions;
    }

    public String getRappelExercice() {
        return rappelExercice;
    }

    public void setRappelExercice(String rappelExercice) {
        this.rappelExercice = rappelExercice;
    }

    public String getTypeEvaluation() {
        return typeEvaluation;
    }

    public void setTypeEvaluation(String typeEvaluation) {
        this.typeEvaluation = typeEvaluation;
    }

    public String getStatut() {
        return statut;
    }

    public void setStatut(String statut) {
        this.statut = statut;
    }

    public String getDureeEnSeconde() {
        return dureeEnSeconde;
    }

    public void setDureeEnSeconde(String dureeEnSeconde) {
        this.dureeEnSeconde = dureeEnSeconde;
    }

}
