package ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Tbl_Personnel".
 */
public class Personnel {

    private Long persId;
    private String sdeId;
    private String nom;
    private String prenom;
    private String sexe;
    private String nomUtilisateur;
    private String motDePasse;
    private String email;
    private String deptId;
    private String comId;
    private String vqseId;
    private String zone;
    private String codeDistrict;
    private Boolean estActif;
    private Integer ProfileId;
    private String dateDebutCollecte;
    private String dateFinCollecte;

    public Personnel() {
    }

    public Personnel(Long persId) {
        this.persId = persId;
    }

    public Personnel(Long persId, String sdeId, String nom, String prenom, String sexe, String nomUtilisateur, String motDePasse, String email, String deptId, String comId, String vqseId, String zone, String codeDistrict, Boolean estActif, Integer ProfileId, String dateDebutCollecte, String dateFinCollecte) {
        this.persId = persId;
        this.sdeId = sdeId;
        this.nom = nom;
        this.prenom = prenom;
        this.sexe = sexe;
        this.nomUtilisateur = nomUtilisateur;
        this.motDePasse = motDePasse;
        this.email = email;
        this.deptId = deptId;
        this.comId = comId;
        this.vqseId = vqseId;
        this.zone = zone;
        this.codeDistrict = codeDistrict;
        this.estActif = estActif;
        this.ProfileId = ProfileId;
        this.dateDebutCollecte = dateDebutCollecte;
        this.dateFinCollecte = dateFinCollecte;
    }

    public Long getPersId() {
        return persId;
    }

    public void setPersId(Long persId) {
        this.persId = persId;
    }

    public String getSdeId() {
        return sdeId;
    }

    public void setSdeId(String sdeId) {
        this.sdeId = sdeId;
    }

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPrenom() {
        return prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public String getSexe() {
        return sexe;
    }

    public void setSexe(String sexe) {
        this.sexe = sexe;
    }

    public String getNomUtilisateur() {
        return nomUtilisateur;
    }

    public void setNomUtilisateur(String nomUtilisateur) {
        this.nomUtilisateur = nomUtilisateur;
    }

    public String getMotDePasse() {
        return motDePasse;
    }

    public void setMotDePasse(String motDePasse) {
        this.motDePasse = motDePasse;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getDeptId() {
        return deptId;
    }

    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    public String getComId() {
        return comId;
    }

    public void setComId(String comId) {
        this.comId = comId;
    }

    public String getVqseId() {
        return vqseId;
    }

    public void setVqseId(String vqseId) {
        this.vqseId = vqseId;
    }

    public String getZone() {
        return zone;
    }

    public void setZone(String zone) {
        this.zone = zone;
    }

    public String getCodeDistrict() {
        return codeDistrict;
    }

    public void setCodeDistrict(String codeDistrict) {
        this.codeDistrict = codeDistrict;
    }

    public Boolean getEstActif() {
        return estActif;
    }

    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }

    public Integer getProfileId() {
        return ProfileId;
    }

    public void setProfileId(Integer ProfileId) {
        this.ProfileId = ProfileId;
    }

    public String getDateDebutCollecte() {
        return dateDebutCollecte;
    }

    public void setDateDebutCollecte(String dateDebutCollecte) {
        this.dateDebutCollecte = dateDebutCollecte;
    }

    public String getDateFinCollecte() {
        return dateFinCollecte;
    }

    public void setDateFinCollecte(String dateFinCollecte) {
        this.dateFinCollecte = dateFinCollecte;
    }

}
