package ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities.Question_FormulaireExercices;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "Tbl_Question_FormulaireExercices".
*/
public class Question_FormulaireExercicesDao extends AbstractDao<Question_FormulaireExercices, Void> {

    public static final String TABLENAME = "Tbl_Question_FormulaireExercices";

    /**
     * Properties of entity Question_FormulaireExercices.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property CodeFormulaireExercice = new Property(0, Long.class, "codeFormulaireExercice", false, "codeFormulaireExercice");
        public final static Property CodeQuestion = new Property(1, Long.class, "codeQuestion", false, "codeQuestion");
        public final static Property OrdreQuestion = new Property(2, String.class, "ordreQuestion", false, "ordreQuestion");
        public final static Property EstDebutQuestion = new Property(3, Boolean.class, "estDebutQuestion", false, "estDebutQuestion");
    };


    public Question_FormulaireExercicesDao(DaoConfig config) {
        super(config);
    }
    
    public Question_FormulaireExercicesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"Tbl_Question_FormulaireExercices\" (" + //
                "\"codeFormulaireExercice\" INTEGER," + // 0: codeFormulaireExercice
                "\"codeQuestion\" INTEGER," + // 1: codeQuestion
                "\"ordreQuestion\" TEXT," + // 2: ordreQuestion
                "\"estDebutQuestion\" INTEGER);"); // 3: estDebutQuestion
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"Tbl_Question_FormulaireExercices\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Question_FormulaireExercices entity) {
        stmt.clearBindings();
 
        Long codeFormulaireExercice = entity.getCodeFormulaireExercice();
        if (codeFormulaireExercice != null) {
            stmt.bindLong(1, codeFormulaireExercice);
        }
 
        Long codeQuestion = entity.getCodeQuestion();
        if (codeQuestion != null) {
            stmt.bindLong(2, codeQuestion);
        }
 
        String ordreQuestion = entity.getOrdreQuestion();
        if (ordreQuestion != null) {
            stmt.bindString(3, ordreQuestion);
        }
 
        Boolean estDebutQuestion = entity.getEstDebutQuestion();
        if (estDebutQuestion != null) {
            stmt.bindLong(4, estDebutQuestion ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public Question_FormulaireExercices readEntity(Cursor cursor, int offset) {
        Question_FormulaireExercices entity = new Question_FormulaireExercices( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // codeFormulaireExercice
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // codeQuestion
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ordreQuestion
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // estDebutQuestion
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Question_FormulaireExercices entity, int offset) {
        entity.setCodeFormulaireExercice(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCodeQuestion(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setOrdreQuestion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEstDebutQuestion(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(Question_FormulaireExercices entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(Question_FormulaireExercices entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
