package ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Tbl_Question_FormulaireExercices".
 */
public class Question_FormulaireExercices {

    private Long codeFormulaireExercice;
    private Long codeQuestion;
    private String ordreQuestion;
    private Boolean estDebutQuestion;

    public Question_FormulaireExercices() {
    }

    public Question_FormulaireExercices(Long codeFormulaireExercice, Long codeQuestion, String ordreQuestion, Boolean estDebutQuestion) {
        this.codeFormulaireExercice = codeFormulaireExercice;
        this.codeQuestion = codeQuestion;
        this.ordreQuestion = ordreQuestion;
        this.estDebutQuestion = estDebutQuestion;
    }

    public Long getCodeFormulaireExercice() {
        return codeFormulaireExercice;
    }

    public void setCodeFormulaireExercice(Long codeFormulaireExercice) {
        this.codeFormulaireExercice = codeFormulaireExercice;
    }

    public Long getCodeQuestion() {
        return codeQuestion;
    }

    public void setCodeQuestion(Long codeQuestion) {
        this.codeQuestion = codeQuestion;
    }

    public String getOrdreQuestion() {
        return ordreQuestion;
    }

    public void setOrdreQuestion(String ordreQuestion) {
        this.ordreQuestion = ordreQuestion;
    }

    public Boolean getEstDebutQuestion() {
        return estDebutQuestion;
    }

    public void setEstDebutQuestion(Boolean estDebutQuestion) {
        this.estDebutQuestion = estDebutQuestion;
    }

}
