package ht.ihsi.rgph.rapport.supervision.Backend.DAOEntities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Tbl_Reponses".
 */
public class Reponses {

    private Long codeReponse;
    private Long codeReponseManuel;
    private Long codeQuestion;
    private String libelleReponse;
    private Boolean isCorrect;
    private Integer scoreTotal;
    private Boolean estEnfant;
    private Boolean avoirEnfant;
    private String codeParent;

    public Reponses() {
    }

    public Reponses(Long codeReponse) {
        this.codeReponse = codeReponse;
    }

    public Reponses(Long codeReponse, Long codeReponseManuel, Long codeQuestion, String libelleReponse, Boolean isCorrect, Integer scoreTotal, Boolean estEnfant, Boolean avoirEnfant, String codeParent) {
        this.codeReponse = codeReponse;
        this.codeReponseManuel = codeReponseManuel;
        this.codeQuestion = codeQuestion;
        this.libelleReponse = libelleReponse;
        this.isCorrect = isCorrect;
        this.scoreTotal = scoreTotal;
        this.estEnfant = estEnfant;
        this.avoirEnfant = avoirEnfant;
        this.codeParent = codeParent;
    }

    public Long getCodeReponse() {
        return codeReponse;
    }

    public void setCodeReponse(Long codeReponse) {
        this.codeReponse = codeReponse;
    }

    public Long getCodeReponseManuel() {
        return codeReponseManuel;
    }

    public void setCodeReponseManuel(Long codeReponseManuel) {
        this.codeReponseManuel = codeReponseManuel;
    }

    public Long getCodeQuestion() {
        return codeQuestion;
    }

    public void setCodeQuestion(Long codeQuestion) {
        this.codeQuestion = codeQuestion;
    }

    public String getLibelleReponse() {
        return libelleReponse;
    }

    public void setLibelleReponse(String libelleReponse) {
        this.libelleReponse = libelleReponse;
    }

    public Boolean getIsCorrect() {
        return isCorrect;
    }

    public void setIsCorrect(Boolean isCorrect) {
        this.isCorrect = isCorrect;
    }

    public Integer getScoreTotal() {
        return scoreTotal;
    }

    public void setScoreTotal(Integer scoreTotal) {
        this.scoreTotal = scoreTotal;
    }

    public Boolean getEstEnfant() {
        return estEnfant;
    }

    public void setEstEnfant(Boolean estEnfant) {
        this.estEnfant = estEnfant;
    }

    public Boolean getAvoirEnfant() {
        return avoirEnfant;
    }

    public void setAvoirEnfant(Boolean avoirEnfant) {
        this.avoirEnfant = avoirEnfant;
    }

    public String getCodeParent() {
        return codeParent;
    }

    public void setCodeParent(String codeParent) {
        this.codeParent = codeParent;
    }

}
